[project]
name = "class01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jawwad-ali", email = "alijawwad001@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.52.4",
]

[project.scripts]
class01 = "class01:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
